### ISSUE TITLE
How to upgrade goup ?

### ISSUE THREAD

**Issue by chengyayu** [owenthereal/goup#15]
Question as title.

**Comment by owenthereal** [comment]
@chengyayu For now, run the installer script again will upgrade `goup` to the latest: https://github.com/owenthereal/goup#installation. I'm working on a `goup upgrade` command to self upgrade.

**Comment by chengyayu** [comment]
I used the following instructions to update，it works fine.
```
go get -u github.com/owenthereal/goup/cmd/goup
```
looking forward to your ```goup upgrade``` ❤️

**Comment by owenthereal** [comment]
Added `goup upgrade` in https://github.com/owenthereal/goup/pull/16.
