### ISSUE TITLE
How do I switch between different version?

### ISSUE THREAD

**Issue by tcp404** [owenthereal/goup#24]
How do I switch between different version?
For instance, `nvm` command can switch different version via `nvm use VERSION` and I can try the latest version and the use stable version on development.

**Comment by hdsong2** [comment]
you can use `goup install <installed version>`

**Comment by tcp404** [comment]
Yeah, that is a solution. BTW, why not set a individual sub command like `goup use VERSION`? I think that is not difficult to impleme.

**Comment by alarangeiras** [comment]
I think what you're looking for is served by the `goup `command. A version selector will be displayed

**Comment by tcp404** [comment]
> I think what you're looking for is served by the `goup `command. A version selector will be displayed

emmm... Just like this:
```bash
┌─(~)────────────────────────────────────────────┐
└──> nvm ls
->      v12.9.1
         v15.9.0
         system
default -> v15.9.0
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v15.9.0) (default)
stable -> 15.9 (-> v15.9.0) (default)

┌─(~)────────────────────────────────────────────┐
└──> nvm use v15.9.0  
Now using node v15.9.0 (npm v7.20.1)
```
I had version `12.9.1` and version `15.9.0`. In the meantime the current version is `12.9.1` and I can use the command `nvm use v15.9.0` to switch the current version.

**Comment by owenthereal** [comment]
You can switch versions by just typing `goup`. In https://github.com/owenthereal/goup/pull/30, I added `goup default VERSION` so that you can set a version. When no version is provided, a prompt will be provided as you would see in `goup`.

I'm closing this issue and feel free to reopen this issue if it doesn't work.
