### ISSUE TITLE
Hoping add these features

### ISSUE THREAD

**Issue by polaris1119** [owenthereal/goup#3]
Thank you developing the tool.

Hoping add these features:

- like `gvm list` and `gvm listall`;
- add uninstall

**Comment by owenthereal** [comment]
@polaris1119 Yup, these are good things to add. Can you clarify what the difference between `gvm list` and `gmv listall` is?

**Comment by polaris1119** [comment]
list       - list installed go versions
  listall    - list available versions

**Comment by owenthereal** [comment]
I added:

* `goup list` to list available Go to install
* `goup show` to show all installed Go
* `goup remove` to remove installed Go
