### ISSUE TITLE
[Feature] automatic configure `GOBIN`, `GOROOT` and `GOPATH`

### ISSUE THREAD

**Issue by yeqown** [owenthereal/goup#32]
After I have installed to `goup` , I ran `go version` command, but it failed since `GOROOT` variable is not changed (and I have deleted all go versions installed manually). Exception looks like: 

```sh
go: cannot find GOROOT directory: /usr/local/Cellar/go/1.17/libexec
```

GOROOT is which have deleted by me before I installed `goup`, what I thought should be set by `goup` installtion is
```sh
GOBIN="$HOME/.go/bin"
GOROOT="$HOME/.go/current"
GOMODCACHE="$HOME/.go/pkg/mod"
GOPATH="$HOME/.go"
```

Of course, it's optional for user, but please must provide this feature

**Comment by yeqown** [comment]
@owenthereal

**Comment by owenthereal** [comment]
Does this still happen? On my local, I see that my `GOROOT="/Users/owen/.go/current"`. I would check whether you have other shell scripts overriding the `GO*` env vars.
