### ISSUE TITLE
can not user command ls-ver

### ISSUE THREAD

**Issue by zhuxubin01** [owenthereal/goup#33]
when i use the following command,error happened

`❯ goup ls-ver                                                                                                                         ⏎
Error: exit status 129
Usage:
  goup ls-ver [REGEXP] [flags]

Examples:

  goup ls-ver
  goup ls-ver 1.15

Flags:
  -h, --help   help for ls-ver

Global Flags:
  -v, --verbose   Verbose

FATA[0000] exit status 129 `

**Comment by owenthereal** [comment]
Does this still happen? Please note that `goup ls-ver` is renamted to `goup search`. And this is the result that I got:

```console
$ goup search 1.15
1.15
1.15.1
1.15.2
1.15.3
1.15.4
1.15.5
1.15.6
1.15.7
1.15.8
1.15.9
1.15.10
1.15.11
1.15.12
1.15.13
1.15.14
1.15.15
1.15beta1
1.15rc1
1.15rc2
```

Feel free to reopen if it still happens.
