### ISSUE TITLE
can't install go1.18.1

### ISSUE THREAD

**Issue by YiuTerran** [owenthereal/goup#35]
FATA[0000] no binary release of go1.18.1 for darwin/arm64 at https://dl.google.com/go/go1.18.1.darwin-arm64.tar.gz

**Comment by owenthereal** [comment]
This should work now. It takes a little time for Go to publish the `VERSION` file that points to the latest version: https://github.com/owenthereal/goup/blob/5fa3e2c6f857c63c788f49f120ec577f1a90e437/internal/commands/install.go#L122
