### ISSUE TITLE
Can't install go1.21.0 due to version parsing error

### ISSUE THREAD

**Issue by epoweripione** [owenthereal/goup#54]
[https://go.dev/VERSION?m=text](https://go.dev/VERSION?m=text) now return with timestamp:
```text
go1.21.0
time 2023-08-04T20:14:06Z
```
Now running `goup install` will failed: 
`FATA[0000] parse "https://dl.google.com/go/go1.21.0\ntime 2023-08-04T20:14:06Z.linux-amd64.tar.gz": net/url: invalid control character in URL`

**Comment by xiaosongfu** [comment]
you can use `goup install 1.21.0`, it works for me.

**Comment by xiaosongfu** [comment]
I have made a PR #55 to solve this problem～

**Comment by owenthereal** [comment]
Fixes in https://github.com/owenthereal/goup/pull/55
